@startuml components


package callgraph {

    class CalledFromList {
    }

    class ClassVisitor  { 
    }

' extends EmptyVisitor
    class CliManager {

    }

    class DynamicCallManager {
    }

    class Instrumenter {
    }

    class JCallGraph {
    }

    class MethodCallsList {
    }

    class MethodReport {
    }

    class MethodVisitor {
    }
    package exporters {
        interface IExporter {
            }

        class CSVExporter implements IExporter {
            }
        class ExportFactory {}
    }
}


package com.github.mauricioaniche.ck {
    package util {}
    package metric {}

    class CK {}
    class CKClassResult {}
    class CKMethodResult {}
    class CKNotifier {}
    class CKVisitor {}
    class MetricsExecutor {}
    class ResultWriter {}
    class ResultWriter {}
    class Runner {}
}

package org.apache.bcel <<Node>> {
    class Constant {}
    class JavaClass {}
    class ConstantPoolGen {}
    class MethodGen {}
    class ConstantPool {}
    class EmptyVisitor {}
    class ClassParser {}
    class Method {}
}

package org.eclipse.jdt.core <<Node>> {

}

/' JCG '/

ClassVisitor -left-> DynamicCallManager
ClassVisitor -> MethodVisitor
ClassVisitor -> org.apache.bcel


JCallGraph -> ClassVisitor
JCallGraph -up-> MethodCallsList
JCallGraph -up-> CalledFromList
JCallGraph -> Instrumenter
JCallGraph -down-> Runner
JCallGraph -up-> ExportFactory
JCallGraph -left-> CliManager

MethodCallsList -up-> MethodReport

MethodVisitor -down-> CalledFromList
MethodVisitor -> org.apache.bcel

DynamicCallManager -> org.apache.bcel

ExportFactory -> IExporter

/' CK '/

com.github.mauricioaniche.ck -down-> org.eclipse.jdt.core

Runner -right-> CK
Runner -> ResultWriter

CKVisitor -> CKClassResult
CKVisitor -up-> util
ResultWriter -> CKClassResult
metric -down-> CKClassResult

CKVisitor -> CKMethodResult
ResultWriter -> CKMethodResult
metric -down-> CKMethodResult
CKClassResult -down-> CKMethodResult

MetricsExecutor -down-> CKNotifier

MetricsExecutor -down-> CKVisitor

CK -down-> MetricsExecutor
CK -> util

metric -> util


@enduml


