@startuml

participant JCallGraph as J
participant CliManager as C
participant Options as O 
participant BasicParser as P
participant CommandLine as CL
participant HelpFormatter as H

J -> C : new CliManager()
activate J
activate C
J -> C : main(args)
C -> O : addOption(String, boolean, String)
note right 
Tantas veces como 
opciones se tengan
end note
C -> O : addOptionGroup(OptionGroup)
alt try 
    C -> P : new BasicParser()
    C -> P : parse(Options, String[])
    activate P
    P -> C : cmdLine = CommandLine
    deactivate P
    C -> CL : getOptionValue(String)
    activate CL
    CL -> C : String
    deactivate CL
    alt option == null
        C -> C : throw ParseException
    note right
    Tantas veces como 
    opciones se tengan
    end note
    end
else catch
    C -> H : printHelp(String, Options)
end
deactivate C
deactivate J
@enduml